### ISSUE TITLE
Add health check

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-workflow-agent#3]
Something like `/health` and `200 response with body: OK` like https://www.airbnb.com/health
This should allow monitoring of VWA containers and restarting them if needed.

**Comment by olafmol** [comment]
related to magneticio/vamp#824

**Comment by olafmol** [comment]
We need to define what we exactly are monitoring (ie the container running, or the node.js workflow being active?) and how we will expose this health endpoint (haproxy inside the VWA, a node or Go based "checker" that's running inside the VWA inside another container?)

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp-workflow-agent/issues/14 - we can use :8080 for health checks.
